package com.pursuit.statesappfromscratchsearchview.model;

import java.util.ArrayList;
import java.util.List;

public class StateWrapper {

    public final State AL;
    public final State AK;
    public final State AZ;
    public final State AR;
    public final State CA;
    public final State CO;
    public final State CT;
    public final State DE;
    public final State FL;
    public final State GA;
    public final State HI;
    public final State ID;
    public final State IL;
    public final State IN;
    public final State IA;
    public final State KS;
    public final State KY;
    public final State LA;
    public final State ME;
    public final State MD;
    public final State MA;
    public final State MI;
    public final State MN;
    public final State MS;
    public final State MO;
    public final State MT;
    public final State NE;
    public final State NV;
    public final State NH;
    public final State NJ;
    public final State NM;
    public final State NY;
    public final State NC;
    public final State ND;
    public final State OH;
    public final State OK;
    public final State OR;
    public final State PA;
    public final State RI;
    public final State SC;
    public final State SD;
    public final State TN;
    public final State TX;
    public final State UT;
    public final State VT;
    public final State VA;
    public final State WA;
    public final State WV;
    public final State WI;
    public final State WY;

    public StateWrapper(State al, State ak, State az, State ar, State ca, State co, State ct, State de, State fl, State ga, State hi, State id, State il, State in, State ia, State ks, State ky, State la, State me, State md, State ma, State mi, State mn, State ms, State mo, State mt, State ne, State nv, State nh, State nj, State nm, State ny, State nc, State nd, State oh, State ok, State or, State pa, State ri, State sc, State sd, State tn, State tx, State ut, State vt, State va, State wa, State wv, State wi, State wy) {
        AL = al;
        AK = ak;
        AZ = az;
        AR = ar;
        CA = ca;
        CO = co;
        CT = ct;
        DE = de;
        FL = fl;
        GA = ga;
        HI = hi;
        ID = id;
        IL = il;
        IN = in;
        IA = ia;
        KS = ks;
        KY = ky;
        LA = la;
        ME = me;
        MD = md;
        MA = ma;
        MI = mi;
        MN = mn;
        MS = ms;
        MO = mo;
        MT = mt;
        NE = ne;
        NV = nv;
        NH = nh;
        NJ = nj;
        NM = nm;
        NY = ny;
        NC = nc;
        ND = nd;
        OH = oh;
        OK = ok;
        OR = or;
        PA = pa;
        RI = ri;
        SC = sc;
        SD = sd;
        TN = tn;
        TX = tx;
        UT = ut;
        VT = vt;
        VA = va;
        WA = wa;
        WV = wv;
        WI = wi;
        WY = wy;
    }

}
